# -*- coding: utf-8 -*-
"""pandas project-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jLaru5YoQKPHcfoVN7ofP4KL2K8uXLqN
"""

import pandas as pd

data=pd.read_csv("Ecommerce Purchases")

data.head(10)

data.tail(10)

data.dtypes #data types of each columns

data.isnull().sum() #to check number of null values of dataset

data.columns #to display all columns names in data set

len(data.columns)

len(data)#to ckeck number of rows

data.info() #both columns and rows detaailed information

data['Purchase Price'].min() #to check lowest purchase price

data['Purchase Price'].max() #highest purchase price

data['Purchase Price'].mean() #average purchase price

len(data[data['Language']=='fr']) #to check how many know perticular language

(data['Language']=='fr').sum() #alternative

data[data['Language']=='fr'].count()

data.columns

data[data['Job'].str.contains('engineer')]

data[data['Job'].str.contains('engineer',case=False)].count() #to calculate no of engineers working #cse for to make insensitive to case

data.columns

data[data['IP Address'] == '132.207.160.22']['Email'] #to get email adress corresponding to perticular data(ip address in this case)

Master_holder=data[data['CC Provider']== 'Mastercard'] #to check user using mastercard's credit card

Master_holder[Master_holder['Purchase Price']>=50].count()# to check user using mastercard's credit and making purchase of >50

data[(data['CC Provider']== 'Mastercard') & (data['Purchase Price']>=50)].count() #alternative

data.columns

data[data['Credit Card']==4664825258997302]['Email'] #to find email corresponding to specific card details

x=len(data[data['AM or PM']=='AM']);x #how many customers made purchase at AM

len(data)-x

data['AM or PM'].value_counts() #alternative

data['CC Exp Date']

def fun():#to check expiry date of cards
  count=0
  for x in data['CC Exp Date']:
    if x.split('/')[1]=='20':
      count+=1
  print(count)

fun()

data['CC Exp Date'].apply(lambda x:x[3:]=='20').sum()#same by using lambda

data.columns

data['Upd_email']=data['Email'].apply(lambda x:x.split('@')[1])

data['Upd_email'].head()#to know top 5 mails cateogary provided by cousumers



